export let questions = [
  {
    question: "Who made the movie Jurassic Park?",
    imgSrc: "./styles/image/tRex.gif",
    answers: [
      "James Cameron",
      "Terrence Malik",
      "Peter Jackson",
      "Steven Spielberg",
    ],
    correctIndex: 3,
    level: "easy",
  },
  {
    question: "In which movie can we hear 'Rosebud'?",
    imgSrc: "./styles/image/Rosebud2.jpg",
    answers: [
      "Macadam Cowboy",
      "How green was my valley",
      "Citizen kane",
      "The night of the Hunter",
    ],
    correctIndex: 2,
    level: "normal",
  },
  {
    question:
      "In which Star Wars movie, the character of Jar Jar Binks appears for the first time?",
    imgSrc: "./styles/image/Jarjarbinks2.jpg",
    answers: [
      "Episode 1: The Phantom Menace",
      "Episode 5: The Empire strikes back",
      "Episode 3: Revenge of the Sith",
      "Episode 2: Attack of the Clones",
    ],
    correctIndex: 0,
    level: "easy",
  },
  {
    question: "Who says 'You are gonna need a bigger boat!'? ",
    imgSrc: "./styles/image/jaws2.jpg",
    answers: [
      "Steve Zissou (The life aquatic)",
      "Chief Martin Brody (Jaws)",
      "Jack Dawson (Titanic)",
      "Richard Philips (Captain Philips)",
    ],
    correctIndex: 1,
    level: "easy",
  },
  {
    question: "In the movie Alien, how many members crew there are? ",
    imgSrc: "./styles/image/Alien2.jpg",
    answers: [
      "One, they all died",
      "Eight, with the Alien",
      "Seven, don't be stupid",
      "Nine, you forgot the cat",
    ],
    correctIndex: 2,
    level: "easy",
  },
  {
    question: "What is the name of the rat in 'Ratatouille'?",
    imgSrc: "./styles/image/Movie-review-Ratatouille2.jpg",
    answers: ["Ratatouille", "Emile", "Auguste Gusteau", "Rémy"],
    correctIndex: 3,
    level: "normal",
  },
  {
    question:
      "What is the most Disney animation movie viewed on the box-office?",
    imgSrc: "./styles/image/disney2.jpg",
    answers: ["Lion King (1994)", "Frozen", "Lion King (2019)", "Snow White"],
    correctIndex: 2,
    level: "normal",
  },
  {
    question: "Who plays the main character in the movie Ben-Hur?",
    imgSrc: "./styles/image/BenHur2.jpg",
    answers: [
      "Jack Hawkins",
      "Charlton Heston",
      "Gregory Peck",
      "Kirk Douglas",
    ],
    correctIndex: 1,
    level: "normal",
  },
  {
    question: "Who says 'I am too old for this shit'?",
    imgSrc: "./styles/image/tooOld.jpg",
    answers: [
      "Roger Murtaugh (The lethal weapon)",
      "Axel Foley (Beverly Hills cop)",
      "John McClane (Die Hard)",
      "John Spartan (Demolition Man)",
    ],
    correctIndex: 0,
    level: "easy",
  },
  {
    question: "Who says 'I am your father'?",
    imgSrc: "./styles/image/luke.gif",
    answers: ["Your father", "Chewbaca", "Darth Vader", "Noooooo"],
    correctIndex: 2,
    level: "easy",
  },
  {
    question:
      "Which William Shakespeare's play inspired the film 'West Side Story'?",
    imgSrc: "./styles/image/westsidestory.gif",
    answers: ["Hamlet", "Macbeth", "Romeo and Juliet", "Othello"],
    correctIndex: 2,
    level: "normal",
  },
  {
    question: "In which movie Clint Eastwood dies on screen?",
    imgSrc: "./styles/image/clintEastwood2.jpg",
    answers: [
      "The Bridges of Madison county",
      "Gran Torino",
      "Space cowboys",
      "A fistful of dollars",
    ],
    correctIndex: 1,
    level: "normal",
  },
  {
    question: "'The Magnificent seven' is a remake of which movie?",
    imgSrc: "./styles/image/7mercenaires2.jpg",
    answers: ["Kagemusha", "12 Angry men", "Furyo", "Seven samurai"],
    correctIndex: 3,
    level: "hard",
  },
  {
    question: "3 films won 11 oscars, which of them?",
    imgSrc: "./styles/image/oscar2.jpg",
    answers: [
      "Ben-Hur, Titanic, The Return of the king",
      "Avatar, Titanic, West Side Story",
      "The English patient, Gigi, The Last emperor",
      "Ben-hur, Titanic, Avatar",
    ],
    correctIndex: 0,
    level: "hard",
  },
  {
    question: "What is the brand of Doc's car in 'Back to the future'?",
    imgSrc: "./styles/image/backtofuture.gif",
    answers: [
      "Chevrolet Camaro",
      "Pontiac GTO",
      "DMC DeLorean",
      "Ford Mustang",
    ],
    correctIndex: 2,
    level: "easy",
  },
  {
    question: "Which animation movie won an Oscar for the song 'Let it go'?",
    imgSrc: "./styles/image/disney2.jpg",
    answers: ["Tangled", "Moana", "Frozen", "Mulan"],
    correctIndex: 2,
    level: "easy",
  },
  {
    question: "What is the breed of the famous dog Lassie?",
    imgSrc: "./styles/image/lassie2.webp",
    answers: [
      "Alaskan Malamute",
      "German Sheperd",
      "Border Collie",
      "Rough Collie",
    ],
    correctIndex: 3,
    level: "hard",
  },
  {
    question: "What is Indiana Jones' biggest fear?",
    imgSrc: "./styles/image/Indiana.gif",
    answers: ["Snakes", "Rats", "Spiders", "Dogs"],
    correctIndex: 0,
    level: "normal",
  },
  {
    question:
      "What is the song played during the ear-cutting scene in 'Reservoir dog' movie? ",
    imgSrc: "./styles/image/reservoirDog.gif",
    answers: [
      "Jungle boogie by Kool & the Gang",
      "Stuck in the middle with you by Stealers Wheel",
      "Street life by Randy Crawford",
      "Bang bang by Nancy Sinatra",
    ],
    correctIndex: 1,
    level: "hard",
  },
  {
    question:
      "In the movie 'Pulp fiction', which weapon choose Bruce Willis to rescue Ving Rhames' character?",
    imgSrc: "./styles/image/pulpFIction.gif",
    answers: ["hammer", "Baseball bat", "Chainsaw", "Katana"],
    correctIndex: 3,
    level: "hard",
  },
  {
    question: "Who plays the talk show host in the movie 'Joker' (2019)?",
    imgSrc: "./styles/image/joker.gif",
    answers: [
      "Joaquin Phoenix",
      "Robert De Niro",
      "Anthony Hopkins",
      "Heath Ledger",
    ],
    correctIndex: 1,
    level: "hard",
  },
  {
    question:
      "What is the name of Dwayne Johnson's character in the movie 'Moana'?",
    imgSrc: "./styles/image/moana2.png",
    answers: ["Moana", "Tala", "Maui", "Tamatoa"],
    correctIndex: 2,
    level: "hard",
  },
  {
    question:
      "Georges Lazenby played James Bond only once, what was the movie?",
    imgSrc: "./styles/image/bond2.webp",
    answers: [
      "Godlfinger",
      "Dr. No",
      "Octopussy",
      "On her Majesty's secret service",
    ],
    correctIndex: 3,
    level: "hard",
  },
  {
    question: "Who provided Groot's voice in Guardians of the galaxy?",
    imgSrc: "./styles/image/baby-groot2.jpg",
    answers: ["Vin Diesel", "Dwayne Johnson", "Chris Pratt", "Bradley Cooper"],
    correctIndex: 0,
    level: "easy",
  },
  {
    question:
      "How many members form the fellowship of the ring in the film series 'The Lord of the rings'?",
    imgSrc: "./styles/image/lordOftherings2.png",
    answers: ["6", "9", "7", "8"],
    correctIndex: 1,
    level: "normal",
  },
  {
    question: "Which movie won the most of prizes all over the world?",
    imgSrc: "./styles/image/palmedor2.jpg",
    answers: ["Parasite", "12 Years a slave", "Gravity", "Mad Max: Fury road"],
    correctIndex: 0,
    level: "hard",
  },
  {
    question: "True lies is a remake of which french movie?",
    imgSrc: "./styles/image/True-Lies2.jpg",
    answers: [
      "La Totale",
      "OSS 117",
      "Gazon maudit",
      "Le père noël est une ordure",
    ],
    correctIndex: 0,
    level: "normal",
  },
  {
    question:
      "Which name is source of trouble in the french movie 'Le Prénom'?",
    imgSrc: "./styles/image/lePrénom2.jpeg",
    answers: ["Adolph", "Adolf", "Adolphe", "Adaulf"],
    correctIndex: 2,
    level: "normal",
  },
  {
    question:
      "What is the answer to the ultimate question of life, the universe, and everything in the movie 'The Hichhiker's guide to the galaxy?",
    imgSrc: "./styles/image/h2g22.jpeg",
    answers: ["there is no answer", "42", "D: la réponse D", "No idea"],
    correctIndex: 1,
    level: "easy",
  },
  {
    question: "What is the full name of Zorg in 'The Fifth element'?",
    imgSrc: "./styles/image/zorg.jpeg",
    answers: [
      "Jean-Baptiste Emanuel Zorg",
      "Jean-Emanuel Zorg",
      "Zorg",
      "Korben Zork",
    ],
    correctIndex: 0,
    level: "hard",
  },
  {
    question: "Who is the actor of Captain America?",
    imgSrc: "./styles/image/captainAmerica2.jpeg",
    answers: ["Chris Hemsworth", "Chris Evans", "Chris Pine", "Chris Pratt"],
    correctIndex: 1,
    level: "hard",
  },
  {
    question: "In which Ghibli movie we can see the character of Haku?",
    imgSrc: "./styles/image/haku2.png",
    answers: [
      "Castle in the sky",
      "My neighbor Totoro",
      "Howl's moving castle",
      "Spirited away",
    ],
    correctIndex: 3,
    level: "normal",
  },
  {
    question: "Who is the director of the movie Point break?",
    imgSrc: "./styles/image/pointBreak.jpg",
    answers: [
      "Kathryn Bigelow",
      "Sofia Coppola",
      "Robert Zemeckis",
      "Michael Bay",
    ],
    correctIndex: 0,
    level: "hard",
  },
  {
    question: "Who is the main actress of 'Some like it hot'?",
    imgSrc: "./styles/image/marilynMonroe2.jpg",
    answers: [
      "Audrey Hepburn",
      "Greta Garbo",
      "Marilyn Monroe",
      "Marlene Dietrich",
    ],
    correctIndex: 2,
    level: "normal",
  },
  {
    question:
      "Who says 'You shall not pass!' in 'The Lord of the rings' movie?",
    imgSrc: "./styles/image/balrog.gif",
    answers: [
      "Frodo Baggins",
      "Aragorn",
      "Samwise Gamgee",
      "Gandalf the Grey",
    ],
    correctIndex:3,
    level:"easy",
  },
  {
    question: "Who is the main actress of 'Pretty woman' movie?",
    imgSrc:"./styles/image/prettyWoman2.jpg",
    answers:["Julia Roberts", "Catherine Zeta-Jones", "Cameron Diaz","Jennifer Aniston"],
    correctIndex: 0,
    level:"easy",

  },
  {
    question: "In the movie 'The Groundhog day', what happens to Phil Connors? ",
    imgSrc:"./styles/image/groundhog.gif",
    answers:["he gets bite by a groundhog","he is trapped in a time loop","he loses his memory","he travels through time"],
    correctIndex:1,
    level:"normal",
  }
];
